import { roster } from "./build.mjs";

/* Existing factions, expanded. Ten-stars are hand-tuned and carry a signature ability. */

export const SAMURAI = roster(
  { faction: "SAM", className: "Samurai", themes: ["Samurai"], keywords: ["Discipline"] },
  [
    ["Ash-Pike Conscript", 1, "foot", "Levied from the kiln villages, given a pike and a direction.", { p: ["ABL_X_IRON_STANCE"] }],
    ["Rope-Sandal Runner", 1, "skirmisher", "Carries orders faster than the horses can be saddled."],
    ["Emberline Archer", 2, "archer", "Trained to loose on the drumbeat and not before."],
    ["Kiln-Gate Spearman", 2, "foot", "Holds the pottery road where the smoke is thickest.", { p: ["ABL_X_IRON_STANCE"] }],
    ["Lacquer Shield Bearer", 3, "guardian", "Twelve coats of lacquer, one for each year of service.", { p: ["ABL_X_IRON_STANCE"] }],
    ["Wave-Cut Ronin", 3, "bruiser", "Masterless, but the cut remembers its school.", { a: ["ABL_X_DRAWN_ARC"] }],
    ["Storm-Petal Naginata", 4, "foot", "Sweeps the low line so the archers keep their footing.", { p: ["ABL_X_IRON_STANCE"] }],
    ["Ash Falcon Outrider", 4, "cavalry", "Rides the ridge lines and reports what the smoke hides.", { a: ["ABL_X_DRAWN_ARC"] }],
    ["Retainer of the Dawn Edge", 5, "second", "Keeps the commander's seal and the commander's temper.", { a: ["ABL_LAST_OATH"] }],
    ["Nine-Fold Fletcher", 5, "archer", "Nine arrows nocked, nine names already chosen."],
    ["Iron Chrysanthemum Captain", 6, "leader", "Rebuilt the line at Kiln Gate with forty survivors.", { a: ["ABL_X_BANNER_CALL"] }],
    ["Kiln Warden", 6, "guardian", "Stands in the gateway because the gateway is the province.", { p: ["ABL_X_IRON_STANCE"], a: ["ABL_X_SECOND_CUT"] }],
    ["Duelist of the Red Verandah", 7, "assassin", "Has never fought indoors and never lost outside.", { a: ["ABL_FORMAL_DUEL"] }],
    ["Banner-Sworn Daimyo", 7, "leader", "Swore the banner would not fall; it has not.", { a: ["ABL_COORDINATED_CUT"] }],
    ["Oni-Mask Executioner", 8, "bruiser", "Wears the mask so the province need not learn the face.", { a: ["ABL_X_DRAWN_ARC"], p: ["ABL_X_SECOND_CUT"] }],
    ["Tide-Breaker of the Salt Coast", 8, "colossus", "Held a landing alone until the tide took the boats back.", { p: ["ABL_X_IRON_STANCE"] }],
    ["Sword Saint of the Quiet Province", 9, "bruiser", "Teaches one student a decade; none have surpassed the first.", { a: ["ABL_X_DRAWN_ARC"], p: ["ABL_X_SECOND_CUT"] }],
    ["The Shogun's Silent Hand", 9, "assassin", "Not listed in any muster roll, present at every succession.", { a: ["ABL_FORMAL_DUEL"] }],
    ["Kagaribi, the Unsheathed Dawn", 10, "bruiser",
      "The last sword saint of the old line. Draws once; the province rewrites its maps after.",
      { a: ["ABL_S_TEN_THOUSAND_CUTS"], p: ["ABL_X_SECOND_CUT"], signature: "ABL_S_TEN_THOUSAND_CUTS",
        arrival: "The draw is heard before it is seen: every enemy on the field loses 10 morale." }],
    ["The Hundred-Province Shogun", 10, "leader",
      "Held a hundred provinces with one oath and never needed a second.",
      { a: ["ABL_S_SUNDERING_OATH"], p: ["ABL_X_OATHLIGHT"], signature: "ABL_S_SUNDERING_OATH",
        arrival: "Every allied Samurai stands: allies recover 25 morale and Broken doctrine counts as Reduced." }],
  ],
);

export const SHINOBI = roster(
  { faction: "SHI", className: "Shinobi", themes: ["Shinobi"], keywords: ["Concealment"] },
  [
    ["Ditch-Lantern Scout", 1, "skirmisher", "Carries an unlit lantern; the light is for leaving, not arriving."],
    ["Paper-Wall Listener", 1, "support", "Paid by the sentence, never by the hour."],
    ["Kite-String Archer", 2, "archer", "Ranges by kite line, looses by memory."],
    ["Sedge-Mask Infiltrator", 2, "skirmisher", "Enters as a reed cutter, leaves as nobody.", { p: ["ABL_X_POISONED_EDGE"] }],
    ["Cistern Runner", 3, "skirmisher", "Knows which wells connect and which only look like they do.", { a: ["ABL_X_SHADOWSTEP"] }],
    ["Split-Tongue Forger", 3, "support", "Has signed forty seals, none of them twice."],
    ["Rain-Gutter Assassin", 4, "assassin", "Waits for the third night of rain, never the first.", { p: ["ABL_X_THROAT_OF_NIGHT"] }],
    ["Hollow-Reed Diver", 4, "skirmisher", "Breathes through a reed for as long as the guard shift lasts.", { a: ["ABL_X_FALSE_TRAIL"] }],
    ["Lieutenant of the Quiet Ledger", 5, "second", "Keeps the debts that keep the network.", { a: ["ABL_SMOKE_RELAY"] }],
    ["Mirror-Lamp Illusionist", 5, "mage", "Sells the same room to three different watchmen.", { a: ["ABL_X_FALSE_TRAIL"] }],
    ["Jonin of the Sedge Gate", 6, "leader", "Has not been seen by a superior in nine years and is still obeyed.", { a: ["ABL_SILENT_DIRECTIVE"] }],
    ["Nightingale-Floor Breaker", 6, "assassin", "Crosses singing floors without waking the song.", { p: ["ABL_X_THROAT_OF_NIGHT"], a: ["ABL_X_SHADOWSTEP"] }],
    ["Ash-Vein Poisoner", 7, "support", "Works in three doses: sleep, silence, and the last one.", { p: ["ABL_X_POISONED_EDGE"] }],
    ["Sky-Hook Rooftop Adept", 7, "skirmisher", "Fights only above the second storey.", { a: ["ABL_X_SHADOWSTEP"], p: ["ABL_X_POISONED_EDGE"] }],
    ["Severed-Name Handler", 8, "leader", "Runs six cells; none of them know the other five exist.", { a: ["ABL_SILENT_DIRECTIVE"], p: ["ABL_X_THROAT_OF_NIGHT"] }],
    ["Twin-Shade Executioner", 8, "assassin", "Arrives twice; only one of the arrivals is real.", { a: ["ABL_TWIN_ECHO"] }],
    ["The Widow of the Salt Ledger", 9, "assassin", "Collected every debt in the ledger and then burned it.", { a: ["ABL_X_SHADOWSTEP"], p: ["ABL_X_THROAT_OF_NIGHT"] }],
    ["Grandmaster of the Unwritten School", 9, "leader", "The school has no scrolls; losing a student loses a technique forever.", { a: ["ABL_SILENT_DIRECTIVE"] }],
    ["Yoi, the Hundred Shadows", 10, "assassin",
      "Nobody has confirmed she is one person. Four of her have been killed; the killings changed nothing.",
      { a: ["ABL_S_HUNDRED_SHADOWS"], p: ["ABL_X_THROAT_OF_NIGHT"], signature: "ABL_S_HUNDRED_SHADOWS",
        arrival: "Every enemy commander is Exposed for one round; nothing on the field can Hide from this unit." }],
    ["The Moonless Verdict", 10, "assassin",
      "Not a name — a sentence passed. Those who hear it read do not hear it finished.",
      { a: ["ABL_S_MOONLESS_VERDICT"], p: ["ABL_X_POISONED_EDGE"], signature: "ABL_S_MOONLESS_VERDICT",
        arrival: "All lights fail: every enemy loses 20 morale and cannot use Overwatch next round." }],
  ],
);

export const KNIGHTS = roster(
  { faction: "KNI", className: "Knight", themes: ["Knight"], keywords: ["Oath"] },
  [
    ["Hedge-Levy Billman", 1, "foot", "Owns a bill, a helm, and a field he would like to return to.", { p: ["ABL_X_SHIELD_LINE"] }],
    ["Chapel Runner", 1, "skirmisher", "Carries the chapter's word between keeps."],
    ["Ivory Wall Crossbow", 2, "archer", "Loads behind the shield line, looses over it."],
    ["Ivory Bastion Man-at-Arms", 2, "foot", "The wall is made of these.", { p: ["ABL_X_SHIELD_LINE"] }],
    ["Gate-Oath Sergeant", 3, "guardian", "Swore at the gate, will be buried in it.", { p: ["ABL_X_SHIELD_LINE"], a: ["ABL_X_INTERPOSE"] }],
    ["Lamp-Vigil Squire", 3, "support", "Keeps the vigil lamps that mark the watch line."],
    ["Blue-Field Lancer", 4, "cavalry", "Trained for one charge per battle and one only.", { a: ["ABL_X_COUCHED_LANCE"] }],
    ["Chapterhouse Warden", 4, "guardian", "Answers to the chapter, not to the crown.", { p: ["ABL_X_SHIELD_LINE"] }],
    ["Castellan of the Second Gate", 5, "second", "Has never opened the second gate and does not intend to.", { a: ["ABL_INHERITED_WALL"] }],
    ["Sun-Chapel Chaplain", 5, "support", "Keeps morale the way an engineer keeps a wall.", { a: ["ABL_X_MENDING_LIGHT"] }],
    ["Marshal of the Ivory Road", 6, "leader", "Holds the road that feeds three keeps.", { a: ["ABL_HOLD_THE_STANDARD"] }],
    ["Oathbreaker Hunter", 6, "bruiser", "Hunts the ones who left; is very good at it.", { a: ["ABL_X_COUCHED_LANCE"] }],
    ["Sky-Lance Dragoon Captain", 7, "cavalry", "Trained his horses to stand under wingbeat.", { a: ["ABL_X_COUCHED_LANCE"], p: ["ABL_X_OATHLIGHT"] }],
    ["Grand Warden of the Ivory Keep", 7, "guardian", "The keep has fallen twice; never while he stood in it.", { p: ["ABL_X_SHIELD_LINE"], a: ["ABL_X_INTERPOSE"] }],
    ["Lord Marshal of the Blue Field", 8, "leader", "Wins by refusing to be anywhere interesting.", { a: ["ABL_HOLD_THE_STANDARD"], p: ["ABL_X_OATHLIGHT"] }],
    ["Champion of the Standing Wall", 8, "colossus", "Two shields, no retreat order in his vocabulary.", { p: ["ABL_X_SHIELD_LINE"], a: ["ABL_X_INTERPOSE"] }],
    ["The Vow-Kept Paladin", 9, "bruiser", "Has kept every vow, including the ones that cost the most.", { p: ["ABL_X_OATHLIGHT"], a: ["ABL_X_INTERPOSE"] }],
    ["High Castellan of the Last Keep", 9, "leader", "Commands the keep that has never been taken.", { a: ["ABL_HOLD_THE_STANDARD"] }],
    ["Aurelane, the Unbreakable Dawn", 10, "guardian",
      "Stood in the breach at Ivory Road for a day and a night. The breach is now a shrine.",
      { a: ["ABL_S_UNBREAKABLE_DAWN"], p: ["ABL_X_OATHLIGHT"], signature: "ABL_S_UNBREAKABLE_DAWN",
        arrival: "The line reforms: allies within 4 are Cleansed, recover 30 morale, and cannot be Routed this round." }],
    ["The Last King's Lance", 10, "cavalry",
      "The king is dead. The lance still rides the muster, and the muster still forms up behind it.",
      { a: ["ABL_S_LANCE_OF_THE_LAST_KING"], p: ["ABL_X_OATHLIGHT"], signature: "ABL_S_LANCE_OF_THE_LAST_KING",
        arrival: "A charge no one ordered: allied Cavalry gain +2 MOV and +300 ATK for two rounds." }],
  ],
);

export const DRAGONS = roster(
  { faction: "DRG", className: "Dragon Host", themes: ["Dragon"], keywords: ["Airborne"] },
  [
    ["Cliff-Nest Fledgling", 1, "flier", "Barely flies. Bites regardless."],
    ["Slate Drake Runt", 1, "flier", "The nest's smallest; the nest's meanest."],
    ["Ash-Gullet Whelp", 2, "flier", "The breath is short and it knows it.", { a: ["ABL_X_BREATH_CONE"] }],
    ["Scree Wyrmling", 2, "flier", "Hunts the talus slopes where footing fails."],
    ["Slate Ridge Drake", 3, "flier", "The Host's standard wing; ranges four ridges a day.", { p: ["ABL_X_SCALED_HIDE"] }],
    ["Thermal-Rider Scout", 3, "flier", "Never flaps where it can climb.", { a: ["ABL_X_STOOP"] }],
    ["Ridge-Claim Drake", 4, "flier", "Territorial to the metre.", { p: ["ABL_X_SCALED_HIDE"], a: ["ABL_X_WINGWASH"] }],
    ["Cinder-Throat Drake", 4, "flier", "Two breaths, then it fights like a beast.", { a: ["ABL_X_BREATH_CONE"] }],
    ["Bonded Wing-Rider", 4, "cavalry", "The rider matters less than the bond."],
    ["Stormvane Harrier", 5, "flier", "Flies the weather other wings refuse.", { a: ["ABL_X_STOOP"] }],
    ["Sky-Ledger Keeper", 5, "second", "Records which ridges the Host has claimed and which it will.", { a: ["ABL_SLIPSTREAM"] }],
    ["Ash-Wake Wyrm", 5, "flier", "Leaves a line of ash where it passed.", { a: ["ABL_X_BREATH_CONE"] }],
    ["Talon-Marshal", 6, "skyleader", "Commands by wing signal; has never used a horn.", { a: ["ABL_WING_ROAR"] }],
    ["Basalt Ridgeback", 6, "colossus", "Walks when it wants to and it rarely wants to.", { p: ["ABL_X_SCALED_HIDE"] }],
    ["Glass-Storm Wyrm", 6, "skymage", "Breathes something between sand and lightning.", { a: ["ABL_X_BREATH_CONE"] }],
    ["Cloud-Splitter Drake", 7, "flier", "Named for the wake, not the weapon.", { a: ["ABL_X_STOOP"], p: ["ABL_X_SCALED_HIDE"] }],
    ["Wyrm-Sworn Dragoon", 7, "cavalry", "Rider and wyrm share a name and refuse to say which came first.", { a: ["ABL_X_COUCHED_LANCE"] }],
    ["Riftwing Claimant", 7, "skyleader", "Holds a rift valley and everything that flies through it.", { a: ["ABL_WING_ROAR"], p: ["ABL_X_SCALED_HIDE"] }],
    ["Obsidian Brood-Mother", 8, "colossus", "Everything on the ridge is either hers or leaving.", { p: ["ABL_X_SCALED_HIDE"], a: ["ABL_X_WINGWASH"] }],
    ["Storm-Gullet Ancient", 8, "skymage", "Old enough to remember when the ridge was a sea.", { a: ["ABL_X_BREATH_CONE"] }],
    ["Vault-Keeper Wyrm", 8, "flier", "Guards a hoard nobody has confirmed exists.", { p: ["ABL_X_SCALED_HIDE"], a: ["ABL_X_STOOP"] }],
    ["The Ridge-Line Tyrant", 9, "colossus", "Has eaten two rival Hosts and their territory claims.", { p: ["ABL_X_SCALED_HIDE"], a: ["ABL_X_BREATH_CONE"] }],
    ["Elder of the Nine Thermals", 9, "skyleader", "Rode the nine thermals in one day; nothing else has.", { a: ["ABL_WING_ROAR"] }],
    ["The Sky-Bound Archon", 9, "skymage", "Speaks in weather. Answers are also weather.", { a: ["ABL_X_BREATH_CONE"], p: ["ABL_X_SCALED_HIDE"] }],
    ["Vharuun, the Skybreaker", 10, "colossus",
      "The Host does not describe him as a dragon. It describes the sky as his and everything else as visiting.",
      { a: ["ABL_S_SKYBREAKER"], p: ["ABL_X_SCALED_HIDE"], signature: "ABL_S_SKYBREAKER",
        arrival: "The air splits: enemy flying units are grounded for a round and every enemy loses 20 morale." }],
    ["Ossuvane, the Territorial Edict", 10, "skyleader",
      "Does not fight for ground. Declares it, and the declaration has never yet been overturned.",
      { a: ["ABL_S_TERRITORIAL_EDICT"], p: ["ABL_X_SCALED_HIDE"], signature: "ABL_S_TERRITORIAL_EDICT",
        arrival: "The edict is spoken: no enemy may fly for two rounds and allied Dragons gain +2 MOV." }],
    ["Kaethyrra, the Wyrmfire Judgement", 10, "skymage",
      "Older than the Host's oldest claim. What she burns is not recorded as lost — it is recorded as settled.",
      { a: ["ABL_S_WYRMFIRE_JUDGEMENT"], p: ["ABL_X_SCALED_HIDE"], signature: "ABL_S_WYRMFIRE_JUDGEMENT",
        arrival: "Everything within 5 hexes catches: enemies take 400 damage and terrain cover burns away." }],
    ["Sunder-Peak Siege Wyrm", 6, "siege", "Brought down a curtain wall by landing on it.", { p: ["ABL_X_SCALED_HIDE"] }],
    ["Gale-Herald", 4, "support", "Reads the wind for the whole wing."],
    ["Nest-Warden Drake", 3, "guardian", "Guards eggs; treats everything else as a threat to eggs.", { p: ["ABL_X_SCALED_HIDE"] }],
  ],
);

export const RITUAL = roster(
  { faction: "RIT", className: "Ritual Cult", themes: ["Ritual Cult"], keywords: ["Channeling"] },
  [
    ["Chalk-Line Acolyte", 1, "support", "Draws the circle; is not permitted inside it."],
    ["Rote-Speaker", 2, "mage", "Knows the words, not the meaning. It is usually enough.", { a: ["ABL_X_LESSER_CIRCLE"], ritual: { knowledge: 2, language: 3, affinity: 1, channeling: 2 } }],
    ["Salt-Ring Warden", 2, "guardian", "Keeps the ring unbroken while others speak."],
    ["Anchor-Stake Keeper", 3, "portal", "Drives the stakes that hold a doorway open.", { a: ["ABL_X_ANCHOR_STAKE"] }],
    ["Foreign Ritualist", 3, "mage", "Speaks four dead languages and one that is not dead yet.", { a: ["ABL_X_LESSER_CIRCLE"], ritual: { knowledge: 3, language: 3, affinity: 2, channeling: 3 } }],
    ["Tongue-Broker", 4, "support", "Sells translations of things that should not be translated.", { p: ["ABL_X_BORROWED_TONGUE"] }],
    ["Circle-Binder", 5, "mage", "Ties two circles together and hopes both hold.", { a: ["ABL_X_LESSER_CIRCLE"], ritual: { knowledge: 4, language: 4, affinity: 3, channeling: 4 } }],
    ["Gate-Second", 5, "second", "Steps in when the speaker's voice gives out.", { a: ["ABL_LAST_OATH"] }],
    ["Hollow Choir", 6, "support", "Nine voices, one of them not counted in the muster."],
    ["Keeper of the Long Door", 6, "portal", "Has kept one door open for eleven years.", { a: ["ABL_X_ANCHOR_STAKE"] }],
    ["Speaker of the Threefold Name", 7, "mage", "Says two thirds of it aloud.", { a: ["ABL_X_LESSER_CIRCLE"], ritual: { knowledge: 5, language: 5, affinity: 4, channeling: 5 } }],
    ["Anchor-Breaker", 7, "assassin", "Employed exclusively against other cults.", { p: ["ABL_X_BORROWED_TONGUE"] }],
    ["Hierophant of the Marsh Rite", 8, "leader", "Runs the rite that made the marsh.", { a: ["ABL_X_LESSER_CIRCLE"], ritual: { knowledge: 6, language: 6, affinity: 5, channeling: 6 } }],
    ["The Unfinished Sentence", 9, "mage", "Halfway through an invocation begun four decades ago.", { a: ["ABL_X_LESSER_CIRCLE"], ritual: { knowledge: 7, language: 7, affinity: 6, channeling: 7 } }],
    ["Vessel of the Long Invitation", 10, "mage",
      "The cult stopped calling it a person some years ago. It still answers to the name, which is the worrying part.",
      { a: ["ABL_S_THE_LONG_INVITATION"], signature: "ABL_S_THE_LONG_INVITATION",
        ritual: { knowledge: 9, language: 9, affinity: 8, channeling: 9 },
        arrival: "Every ritual circle on the field gains three progress and every portal cooldown is cleared." }],
  ],
);

export const THORN_COVEN = roster(
  { faction: "THC", className: "Thorn Coven", themes: ["Thorn"], keywords: ["Briar"] },
  [
    ["Bramble Hedger", 1, "foot", "Cuts hedge by day, plants it back by night.", { p: ["ABL_X_THORNWARD"] }],
    ["Nettle Gleaner", 1, "skirmisher", "Harvests what stings and knows what it is for."],
    ["Thorn-Line Archer", 2, "archer", "Fletches with briar; the wound closes wrong."],
    ["Root-Cellar Warden", 2, "guardian", "Guards the cellar where the coven keeps its winters.", { p: ["ABL_X_THORNWARD"] }],
    ["Blood-Loam Tender", 3, "support", "Feeds the garden what the garden asks for.", { p: ["ABL_X_BLOOD_LOAM"] }],
    ["Snare-Witch", 3, "mage", "Never chases; the ground does that.", { a: ["ABL_X_BRIAR_SNARE"] }],
    ["Hollow-Stem Stalker", 4, "assassin", "Moves through hedge the way water moves through sand.", { p: ["ABL_X_BLOOD_LOAM"] }],
    ["Hex-Sign Cutter", 4, "mage", "Cuts signs into bark; the bark keeps them.", { a: ["ABL_X_HEX_SIGN"] }],
    ["Coven Second", 5, "second", "Holds the coven's second name, spoken only at succession.", { a: ["ABL_LAST_OATH"] }],
    ["Briar-Bound Champion", 5, "bruiser", "Wears the briar; the briar wears back.", { p: ["ABL_X_THORNWARD", "ABL_X_BLOOD_LOAM"] }],
    ["Wormwood Apothecary", 6, "support", "Two shelves: one for keeping people, one for the rest.", { p: ["ABL_X_BLOOD_LOAM"] }],
    ["Mother of Small Thorns", 6, "leader", "Every hedge in the valley reports to her.", { a: ["ABL_X_BRIAR_SNARE"] }],
    ["Gallows-Root Colossus", 7, "colossus", "Grew where the gallows stood and kept the shape.", { p: ["ABL_X_THORNWARD"] }],
    ["Whisper-Bark Hexer", 7, "mage", "The trees repeat what she says, at night, to whoever is passing.", { a: ["ABL_X_HEX_SIGN"], p: ["ABL_X_BLOOD_LOAM"] }],
    ["Warden of the Strangling Grove", 8, "guardian", "The grove has taken four companies; he has taken none of the credit.", { p: ["ABL_X_THORNWARD"], a: ["ABL_X_BRIAR_SNARE"] }],
    ["Crone of the Split Trunk", 8, "leader", "Two voices from one throat, both older than the coven.", { a: ["ABL_X_HEX_SIGN"], p: ["ABL_X_BLOOD_LOAM"] }],
    ["The Red Orchard Keeper", 9, "bruiser", "The orchard bears in winter. Nobody eats from it.", { p: ["ABL_X_THORNWARD", "ABL_X_BLOOD_LOAM"] }],
    ["First Seed of the Coven", 9, "mage", "Claims to be the oldest thing the coven planted.", { a: ["ABL_X_BRIAR_SNARE"], p: ["ABL_X_BLOOD_LOAM"] }],
    ["Sythra, the Garden of Knives", 10, "mage",
      "Where she stands becomes garden. What the garden takes, it keeps standing up, and the standing ones are hers.",
      { a: ["ABL_S_GARDEN_OF_KNIVES"], p: ["ABL_X_THORNWARD"], signature: "ABL_S_GARDEN_OF_KNIVES",
        arrival: "Briars erupt across the field: all Open terrain within 4 becomes Forest and enemies there are rooted." }],
    ["The Root of the World", 10, "colossus",
      "The coven did not plant it. The coven formed around it, and has never agreed on what it is waiting for.",
      { a: ["ABL_S_ROOT_OF_THE_WORLD"], p: ["ABL_X_THORNWARD", "ABL_X_BLOOD_LOAM"], signature: "ABL_S_ROOT_OF_THE_WORLD",
        arrival: "The ground answers: every enemy within 5 is rooted for one round and loses 25 morale." }],
  ],
);
